_commit: v1.12.1-9-g5863ce6
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Media Player
homepageEnabled: true
homepageGroup: Media
homepageIcon: plex
homepageName: Plex
ingHost: plex.crt.lol
ingName: plex
ingress: false
labels: 'app: plex'
name: plex
namespace: plex
pvc: false
reloader: true
resources:
- deployments.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: false
upstreamURL: https://www.plex.tv/
url: https://github.com/charlesthomas/homelab-plex
