_commit: v1.3.6
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: ''
backups: false
helm: false
homepageDescription: Media Player
homepageEnabled: true
homepageGroup: Media
homepageIcon: plex
homepageName: Plex
ingClass: nginx-external
ingCname: crt.house
ingExtraAnnotations: ''
ingHost: plex.crt.house
ingName: plex
ingPathType: Prefix
ingSecret: crt.house
ingWebSockets: false
ingress: true
labels: 'app: plex'
name: plex
namespace: plex
pvc: true
pvcAccessMode: ReadWriteOnce
pvcName: plex-media-server
pvcSize: 25Gi
pvcStorageClass: longhorn-retain
reloader: false
resources:
- deployments.yaml
- ingresses.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
service: true
serviceAccount: true
svcAccountName: plex
svcName: plex
svcPortName: plex
svcPortNum: 32400
svcProtocol: TCP
svcSelector: 'app: plex'
svcTargetPort: plex
svcType: ClusterIP
upstreamURL: https://www.plex.tv/
url: https://github.com/charlesthomas/homelab-plex
