---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex

commonLabels:
  app: plex

resources:
- deployments.yaml
- ingresses.yaml
- namespaces.yaml
- pvcs.yaml
- service-accounts.yaml
- services.yaml
