---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-plex
commonLabels:
  app: plex

images:
  - name: plex
    newName: plexinc/pms-docker
    newTag: 1.42.1.10060-4e8b05daf

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: all
      namespace: plex
      annotations:
        reloader.stakater.com/auto: "true"
  target:
    kind: Deployment

- patch: |-
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: plex
      namespace: plex
      annotations:
        gethomepage.dev/href: https://plex.crt.lol
        gethomepage.dev/enabled: "true"
        gethomepage.dev/description: Media Player
        gethomepage.dev/group: Media
        gethomepage.dev/icon: plex
        gethomepage.dev/name: Plex
        gethomepage.dev/pod-selector: ""
  target:
    kind: Ingress
