---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: plex

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-plex
commonLabels:
  app: plex

resources:
- resources/deployments.yaml
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/pvcs.yaml
- resources/service-accounts.yaml
- resources/services.yaml

images:
  - name: plex
    newName: plexinc/pms-docker
    newTag: 1.41.5.9522-a96edc606
