---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  annotations:
    external-dns.alpha.kubernetes.io/hostname: plex.crt.house
    external-dns.alpha.kubernetes.io/target: crt.house
    gethomepage.dev/href: https://plex.crt.house
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Media Player
    gethomepage.dev/group: Media
    gethomepage.dev/icon: plex
    gethomepage.dev/name: Plex
    gethomepage.dev/pod-selector: ""
spec:
  ingressClassName: nginx-external
  rules:
    - host: "plex.crt.house"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: plex
                port:
                  number: 32400
  tls:
    - hosts:
      - plex.crt.house
      secretName: crt.house
