---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-media-server
  namespace: plex
spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 25Gi
    storageClassName: longhorn-retain
    volumeMode: Filesystem
